variable "region" {}
variable "project_name" {}
variable "codecommit_branch" {}
variable "repository_name" {}
variable "compute_platform" {}
variable "codedeployapp_name" {}
variable "instance_type" {}
variable "key_name" {}
variable "ami" {}
variable "bucket_name" {}